development: &defaults
  app_id: 189368391107072
  client_id: 9232b178f28e3689e1a072a634b68791
  client_secret: 6c7561f89f08dffbb6e557ab0aee3cb8
  perms: email, user_about_me, user_birthday, user_location, user_status, user_likes, user_photos, friends_about_me

test:
  <<: *defaults

production:
  <<: *defaults
